/**
 * Analytics API Routes
 *
 * Endpoints:
 * - GET /api/v1/analytics/llm-stats - Get LLM usage statistics
 * - GET /api/v1/analytics/provider-comparison - Compare provider performance
 * - GET /api/v1/analytics/popular-queries - Get popular queries
 * - GET /api/v1/analytics/cost-report - Get cost breakdown
 * - GET /api/v1/analytics/faq-insights - Get aggregated FAQ insights for SKIDIY platform
 */

const express = require('express');
const router = express.Router();
const AnalyticsService = require('../services/analytics-service');
const AlertService = require('../services/alert-service');
const { AppError } = require('../middleware/error-handler');
const { sendSuccess } = require('../utils/response-formatter');
const requireApiKey = require('../middleware/api-key');
const path = require('path');
const fs = require('fs').promises;

// Initialize Analytics Service
let analyticsService = null;
let alertService = null;

try {
  analyticsService = new AnalyticsService();
  console.log('[Analytics API] Analytics Service initialized');

  // Initialize Alert Service
  alertService = new AlertService(analyticsService, {
    dailyCostLimit: parseFloat(process.env.DAILY_COST_LIMIT) || 10.0,
    monthlyCostLimit: parseFloat(process.env.MONTHLY_COST_LIMIT) || 300.0,
    hourlyRequestLimit: parseInt(process.env.HOURLY_REQUEST_LIMIT) || 100,
    errorRateThreshold: parseFloat(process.env.ERROR_RATE_THRESHOLD) || 10,
    alertCooldown: parseInt(process.env.ALERT_COOLDOWN) || 60,
    enabled: process.env.ALERTS_ENABLED !== 'false'
  });

  // Add console alert handler
  alertService.addHandler((alert) => {
    console.log(`[Alert] ${alert.severity.toUpperCase()}: ${alert.message}`);
  });

  console.log('[Analytics API] Alert Service initialized');
} catch (error) {
  console.error('[Analytics API] Failed to initialize:', error.message);
}

/**
 * GET /api/v1/analytics/llm-stats
 *
 * Get comprehensive LLM usage statistics
 *
 * Query params:
 * - start_date: ISO date string (optional)
 * - end_date: ISO date string (optional)
 * - provider: Provider name filter (optional)
 * - limit: Number of recent queries to return (default: 100)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "overall": {
 *       "totalRequests": 150,
 *       "successfulRequests": 145,
 *       "failedRequests": 5,
 *       "successRate": "96.67",
 *       "totalTokens": 123456,
 *       "totalCost": "1.2345",
 *       "avgResponseTime": 850,
 *       "avgFaqItems": "3.2"
 *     },
 *     "byProvider": [...],
 *     "recent": [...],
 *     "daily": [...]
 *   }
 * }
 */
router.get('/llm-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      start_date: startDate,
      end_date: endDate,
      provider,
      limit = 100
    } = req.query;

    const stats = analyticsService.getLLMStats({
      startDate,
      endDate,
      provider,
      limit: parseInt(limit, 10)
    });

    sendSuccess(res, stats, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/provider-comparison
 *
 * Compare performance across LLM providers (last 30 days)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": [
 *     {
 *       "provider": "gemini",
 *       "totalRequests": 100,
 *       "successRate": "98.00",
 *       "totalTokens": 50000,
 *       "totalCost": "0.1250",
 *       "avgResponseTime": 450,
 *       "costPerRequest": "0.001250"
 *     }
 *   ]
 * }
 */
router.get('/provider-comparison', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const comparison = analyticsService.getProviderComparison();

    sendSuccess(res, comparison, 200, {
      timestamp: new Date().toISOString(),
      period: 'Last 30 days'
    });
  } catch (error) {
    next(error);
  }
});


/**
 * GET /api/v1/analytics/faq-insights
 *
 * Returns aggregated FAQ insights for the SKIDIY platform.
 * Data is generated by the analytics worker and stored as JSON.
 */
router.get('/faq-insights', requireApiKey(), async (req, res, next) => {
  try {
    const summaryPath =
      process.env.FAQ_INSIGHTS_PATH ||
      path.join(__dirname, '../../../data/analytics_summary.json');

    let payloadRaw;
    try {
      payloadRaw = await fs.readFile(summaryPath, 'utf-8');
    } catch (readError) {
      throw new AppError(
        'FAQ_INSIGHTS_NOT_READY',
        'FAQ insights summary file is not available. Ensure analytics worker has generated the file.',
        503,
        { summaryPath }
      );
    }

    let payload;
    try {
      payload = JSON.parse(payloadRaw);
    } catch (parseError) {
      throw new AppError(
        'FAQ_INSIGHTS_INVALID',
        'FAQ insights summary file contains invalid JSON.',
        500,
        { summaryPath }
      );
    }

    if (!payload || typeof payload !== 'object') {
      throw new AppError(
        'FAQ_INSIGHTS_INVALID',
        'FAQ insights payload is missing or malformed.',
        500,
        { summaryPath }
      );
    }

    const {
      topViewedResorts = [],
      topInteractedFaqs = [],
      generated_at: generatedAt = null
    } = payload;

    sendSuccess(
      res,
      {
        topViewedResorts,
        topInteractedFaqs,
        generated_at: generatedAt
      },
      200,
      {
        timestamp: new Date().toISOString(),
        source: 'analytics-summary'
      }
    );
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/popular-queries
 *
 * Get most popular queries (last 7 days)
 *
 * Query params:
 * - limit: Number of queries to return (default: 10)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": [
 *     {
 *       "query_text": "小朋友幾歲可以學滑雪",
 *       "count": 15,
 *       "avg_tokens": 850,
 *       "avg_response_time": 650
 *     }
 *   ]
 * }
 */
router.get('/popular-queries', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { limit = 10 } = req.query;

    const queries = analyticsService.getPopularQueries(parseInt(limit, 10));

    sendSuccess(res, queries, 200, {
      timestamp: new Date().toISOString(),
      period: 'Last 7 days'
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/cost-report
 *
 * Get detailed cost breakdown by provider and model
 *
 * Query params:
 * - start_date: ISO date string (optional)
 * - end_date: ISO date string (optional)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "totalCost": "2.5678",
 *     "byProvider": {
 *       "gemini": {
 *         "cost": "0.1250",
 *         "requests": 100,
 *         "avgCostPerRequest": "0.001250"
 *       },
 *       "claude": {...}
 *     },
 *     "projectedMonthlyCost": "75.00"
 *   }
 * }
 */
router.get('/cost-report', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      start_date: startDate,
      end_date: endDate
    } = req.query;

    // Get stats for cost calculation
    const stats = analyticsService.getLLMStats({ startDate, endDate });

    // Calculate cost breakdown
    const byProvider = {};
    for (const provider of stats.byProvider) {
      byProvider[provider.provider] = {
        cost: (provider.cost || 0).toFixed(4),
        requests: provider.requests,
        avgCostPerRequest: provider.requests > 0
          ? ((provider.cost || 0) / provider.requests).toFixed(6)
          : '0.000000'
      };
    }

    // Project monthly cost (assuming current rate)
    const daysOfData = stats.daily.length || 1;
    const avgDailyCost = parseFloat(stats.overall.totalCost) / daysOfData;
    const projectedMonthlyCost = (avgDailyCost * 30).toFixed(2);

    const costReport = {
      totalCost: stats.overall.totalCost,
      byProvider,
      projectedMonthlyCost,
      dataPoints: {
        startDate: startDate || stats.daily[stats.daily.length - 1]?.date,
        endDate: endDate || stats.daily[0]?.date,
        totalDays: daysOfData
      }
    };

    sendSuccess(res, costReport, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/export
 *
 * Export analytics data as CSV
 *
 * Query params:
 * - type: Export type (llm_usage | provider_stats)
 * - start_date: ISO date string (optional)
 * - end_date: ISO date string (optional)
 *
 * Response: CSV file download
 */
router.get('/export', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      type = 'llm_usage',
      start_date: startDate,
      end_date: endDate
    } = req.query;

    // Get data
    const stats = analyticsService.getLLMStats({ startDate, endDate, limit: 10000 });

    let csv = '';
    let filename = '';

    if (type === 'llm_usage') {
      // Generate CSV for LLM usage
      csv = 'Timestamp,Query,Provider,Model,Tokens,Cost,Response Time,Success\n';
      for (const row of stats.recent) {
        csv += `"${row.timestamp}","${row.query_text.replace(/"/g, '""')}",${row.provider},${row.model},${row.total_tokens},${row.cost_usd || 0},${row.response_time_ms},${row.success}\n`;
      }
      filename = `llm-usage-${new Date().toISOString().split('T')[0]}.csv`;
    } else if (type === 'provider_stats') {
      // Generate CSV for provider comparison
      csv = 'Provider,Requests,Success Rate,Total Tokens,Total Cost,Avg Response Time,Cost Per Request\n';
      const comparison = analyticsService.getProviderComparison();
      for (const row of comparison) {
        csv += `${row.provider},${row.totalRequests},${row.successRate}%,${row.totalTokens},${row.totalCost},${row.avgResponseTime}ms,${row.costPerRequest}\n`;
      }
      filename = `provider-stats-${new Date().toISOString().split('T')[0]}.csv`;
    }

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(csv);
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/alerts/check
 *
 * Check all alert conditions and return triggered alerts
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "alerts": [
 *       {
 *         "type": "DAILY_COST_EXCEEDED",
 *         "severity": "warning",
 *         "message": "每日成本已達 $12.50（限額：$10.00）",
 *         "data": {...},
 *         "timestamp": "2025-10-13T..."
 *       }
 *     ],
 *     "status": {...}
 *   }
 * }
 */
router.get('/alerts/check', async (req, res, next) => {
  try {
    if (!alertService) {
      throw new AppError('SERVICE_UNAVAILABLE', '警報服務尚未初始化', 503);
    }

    const alerts = await alertService.checkAlerts();
    const status = alertService.getAlertStatus();

    sendSuccess(res, {
      alerts,
      status
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/alerts/status
 *
 * Get current alert configuration and status
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "enabled": true,
 *     "config": {...},
 *     "lastAlerts": {...}
 *   }
 * }
 */
router.get('/alerts/status', async (req, res, next) => {
  try {
    if (!alertService) {
      throw new AppError('SERVICE_UNAVAILABLE', '警報服務尚未初始化', 503);
    }

    const status = alertService.getAlertStatus();

    sendSuccess(res, status, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * PUT /api/v1/analytics/alerts/config
 *
 * Update alert configuration
 *
 * Request body:
 * {
 *   "dailyCostLimit": 15.0,
 *   "monthlyCostLimit": 400.0,
 *   "hourlyRequestLimit": 150,
 *   "errorRateThreshold": 15,
 *   "alertCooldown": 30,
 *   "enabled": true
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "config": {...}
 *   }
 * }
 */
router.put('/alerts/config', async (req, res, next) => {
  try {
    if (!alertService) {
      throw new AppError('SERVICE_UNAVAILABLE', '警報服務尚未初始化', 503);
    }

    const {
      dailyCostLimit,
      monthlyCostLimit,
      hourlyRequestLimit,
      errorRateThreshold,
      alertCooldown,
      enabled
    } = req.body;

    const newConfig = {};

    if (dailyCostLimit !== undefined) newConfig.dailyCostLimit = parseFloat(dailyCostLimit);
    if (monthlyCostLimit !== undefined) newConfig.monthlyCostLimit = parseFloat(monthlyCostLimit);
    if (hourlyRequestLimit !== undefined) newConfig.hourlyRequestLimit = parseInt(hourlyRequestLimit);
    if (errorRateThreshold !== undefined) newConfig.errorRateThreshold = parseFloat(errorRateThreshold);
    if (alertCooldown !== undefined) newConfig.alertCooldown = parseInt(alertCooldown);
    if (enabled !== undefined) newConfig.enabled = Boolean(enabled);

    alertService.updateConfig(newConfig);

    sendSuccess(res, {
      config: alertService.config
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/hot-faqs
 *
 * Get most clicked/viewed FAQs (hot/trending FAQs)
 *
 * Query params:
 * - limit: Number of FAQs to return (default: 5)
 * - days: Number of days to look back (default: 7)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "hot_faqs": [
 *       {
 *         "faq_id": "faq.booking.001",
 *         "views": 150,
 *         "clicks": 120,
 *         "click_rate": 0.8
 *       }
 *     ]
 *   }
 * }
 */
router.get('/hot-faqs', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const limit = parseInt(req.query.limit) || 5;
    const days = parseInt(req.query.days) || 7;

    const db = analyticsService.db;
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - days);

    // Get FAQs with most clicks in the last N days
    const hotFAQs = db.prepare(`
      SELECT
        faq_id,
        COUNT(*) as views,
        SUM(CASE WHEN clicked = 1 THEN 1 ELSE 0 END) as clicks,
        ROUND(CAST(SUM(CASE WHEN clicked = 1 THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*), 2) as click_rate
      FROM faq_views
      WHERE timestamp >= ?
      GROUP BY faq_id
      ORDER BY clicks DESC, views DESC
      LIMIT ?
    `).all(cutoffDate.toISOString(), limit);

    sendSuccess(res, {
      hot_faqs: hotFAQs,
      period_days: days,
      total_faqs: hotFAQs.length
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/track-faq-view
 *
 * Track FAQ view/click event
 *
 * Body:
 * {
 *   "faq_id": "faq.booking.001",
 *   "clicked": true,
 *   "query_id": 123,
 *   "position": 1,
 *   "time_to_click_ms": 1500
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": { "tracked": true }
 * }
 */
router.post('/track-faq-view', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { faq_id, clicked, query_id, position, time_to_click_ms } = req.body;

    if (!faq_id) {
      throw new AppError('VALIDATION_ERROR', 'faq_id 為必填欄位', 400);
    }

    const db = analyticsService.db;

    // Insert view record
    const stmt = db.prepare(`
      INSERT INTO faq_views (faq_id, query_id, position, clicked, time_to_click_ms)
      VALUES (?, ?, ?, ?, ?)
    `);

    stmt.run(
      faq_id,
      query_id || null,
      position || 0,
      clicked ? 1 : 0,
      time_to_click_ms || null
    );

    sendSuccess(res, {
      tracked: true,
      faq_id
    }, 201, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/track-section-view
 *
 * Track section click event
 *
 * Body:
 * {
 *   "section": "booking",
 *   "language": "zh"
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": { "tracked": true }
 * }
 */
router.post('/track-section-view', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { section, language = 'zh' } = req.body;

    if (!section) {
      throw new AppError('VALIDATION_ERROR', 'section 為必填欄位', 400);
    }

    const db = analyticsService.db;

    // Insert section view record
    const stmt = db.prepare(`
      INSERT INTO section_views (section, language)
      VALUES (?, ?)
    `);

    stmt.run(section, language);

    sendSuccess(res, {
      tracked: true,
      section
    }, 201, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/section-stats
 *
 * Get section click statistics
 *
 * Query params:
 * - days: Number of days to look back (default: 30)
 * - language: Filter by language (optional)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "total": 150,
 *     "by_section": [
 *       {"section": "booking", "clicks": 50, "percentage": "33.33"},
 *       {"section": "gear", "clicks": 30, "percentage": "20.00"}
 *     ],
 *     "by_language": [...],
 *     "daily": [...]
 *   }
 * }
 */
router.get('/section-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { days = 30, language } = req.query;
    const db = analyticsService.db;

    const daysAgo = new Date();
    daysAgo.setDate(daysAgo.getDate() - parseInt(days, 10));
    const dateFilter = daysAgo.toISOString();

    // Total clicks
    let totalQuery = `SELECT COUNT(*) as total FROM section_views WHERE timestamp >= ?`;
    const params = [dateFilter];

    if (language) {
      totalQuery += ` AND language = ?`;
      params.push(language);
    }

    const totalResult = db.prepare(totalQuery).get(...params);
    const total = totalResult.total;

    // By section
    let bySectionQuery = `
      SELECT
        section,
        COUNT(*) as clicks,
        ROUND(COUNT(*) * 100.0 / ?, 2) as percentage
      FROM section_views
      WHERE timestamp >= ?
    `;
    const bySectionParams = [total, dateFilter];

    if (language) {
      bySectionQuery += ` AND language = ?`;
      bySectionParams.push(language);
    }

    bySectionQuery += ` GROUP BY section ORDER BY clicks DESC`;

    const bySection = db.prepare(bySectionQuery).all(...bySectionParams);

    // By language
    const byLanguageQuery = `
      SELECT
        language,
        COUNT(*) as clicks
      FROM section_views
      WHERE timestamp >= ?
      GROUP BY language
      ORDER BY clicks DESC
    `;
    const byLanguage = db.prepare(byLanguageQuery).all(dateFilter);

    // Daily stats
    const dailyQuery = `
      SELECT
        DATE(timestamp) as date,
        section,
        COUNT(*) as clicks
      FROM section_views
      WHERE timestamp >= ?
      GROUP BY DATE(timestamp), section
      ORDER BY date DESC, clicks DESC
      LIMIT 100
    `;
    const daily = db.prepare(dailyQuery).all(dateFilter);

    sendSuccess(res, {
      total,
      by_section: bySection,
      by_language: byLanguage,
      daily,
      period_days: parseInt(days, 10)
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/faq-stats
 *
 * Get detailed FAQ click statistics
 *
 * Query params:
 * - days: Number of days to look back (default: 30)
 * - clicked_only: Only include clicked FAQs (default: true)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "total_views": 500,
 *     "total_clicks": 300,
 *     "click_through_rate": "60.00",
 *     "by_faq": [...],
 *     "daily": [...]
 *   }
 * }
 */
router.get('/faq-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { days = 30, clicked_only = 'true' } = req.query;
    const db = analyticsService.db;

    const daysAgo = new Date();
    daysAgo.setDate(daysAgo.getDate() - parseInt(days, 10));
    const dateFilter = daysAgo.toISOString();

    // Total views and clicks
    const totalsQuery = `
      SELECT
        COUNT(*) as total_views,
        SUM(clicked) as total_clicks
      FROM faq_views
      WHERE timestamp >= ?
    `;
    const totals = db.prepare(totalsQuery).get(dateFilter);
    const clickThroughRate = totals.total_views > 0
      ? ((totals.total_clicks / totals.total_views) * 100).toFixed(2)
      : '0.00';

    // By FAQ
    let byFaqQuery = `
      SELECT
        faq_id,
        COUNT(*) as views,
        SUM(clicked) as clicks,
        ROUND(SUM(clicked) * 100.0 / COUNT(*), 2) as ctr
      FROM faq_views
      WHERE timestamp >= ?
    `;

    if (clicked_only === 'true') {
      byFaqQuery += ` AND clicked = 1`;
    }

    byFaqQuery += ` GROUP BY faq_id ORDER BY clicks DESC LIMIT 50`;

    const byFaq = db.prepare(byFaqQuery).all(dateFilter);

    // Enrich FAQ data with titles from faq_kb.js
    const faqKB = require('../data/faq_kb.js');
    const faqMap = {};
    if (faqKB && faqKB.items) {
      faqKB.items.forEach(item => {
        faqMap[item.id] = {
          title: item.canonical_question || item.id,
          section: item.section || ''
        };
      });
    }

    // Add titles to FAQ stats
    const enrichedByFaq = byFaq.map(faq => ({
      ...faq,
      title: faqMap[faq.faq_id]?.title || faq.faq_id,
      section: faqMap[faq.faq_id]?.section || ''
    }));

    // Daily stats
    const dailyQuery = `
      SELECT
        DATE(timestamp) as date,
        COUNT(*) as views,
        SUM(clicked) as clicks
      FROM faq_views
      WHERE timestamp >= ?
      GROUP BY DATE(timestamp)
      ORDER BY date DESC
    `;
    const daily = db.prepare(dailyQuery).all(dateFilter);

    sendSuccess(res, {
      total_views: totals.total_views,
      total_clicks: totals.total_clicks,
      click_through_rate: clickThroughRate,
      by_faq: enrichedByFaq,
      daily,
      period_days: parseInt(days, 10)
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

module.exports = router;
