/**
 * Analytics API Routes
 *
 * Endpoints:
 * - GET /api/v1/analytics/llm-stats - Get LLM usage statistics
 * - GET /api/v1/analytics/provider-comparison - Compare provider performance
 * - GET /api/v1/analytics/popular-queries - Get popular queries
 * - GET /api/v1/analytics/cost-report - Get cost breakdown
 * - GET /api/v1/analytics/faq-insights - Get aggregated FAQ insights for SKIDIY platform
 */

const express = require('express');
const router = express.Router();
const AnalyticsService = require('../services/analytics-service');
const AlertService = require('../services/alert-service');
const { AppError } = require('../middleware/error-handler');
const { sendSuccess } = require('../utils/response-formatter');
const requireApiKey = require('../middleware/api-key');
const path = require('path');
const fs = require('fs').promises;

// Initialize Analytics Service
let analyticsService = null;
let alertService = null;

try {
  analyticsService = new AnalyticsService();
  console.log('[Analytics API] Analytics Service initialized');

  // Initialize Alert Service
  alertService = new AlertService(analyticsService, {
    dailyCostLimit: parseFloat(process.env.DAILY_COST_LIMIT) || 10.0,
    monthlyCostLimit: parseFloat(process.env.MONTHLY_COST_LIMIT) || 300.0,
    hourlyRequestLimit: parseInt(process.env.HOURLY_REQUEST_LIMIT) || 100,
    errorRateThreshold: parseFloat(process.env.ERROR_RATE_THRESHOLD) || 10,
    alertCooldown: parseInt(process.env.ALERT_COOLDOWN) || 60,
    enabled: process.env.ALERTS_ENABLED !== 'false'
  });

  // Add console alert handler
  alertService.addHandler((alert) => {
    console.log(`[Alert] ${alert.severity.toUpperCase()}: ${alert.message}`);
  });

  console.log('[Analytics API] Alert Service initialized');
} catch (error) {
  console.error('[Analytics API] Failed to initialize:', error.message);
}

/**
 * GET /api/v1/analytics/llm-stats
 *
 * Get comprehensive LLM usage statistics
 *
 * Query params:
 * - start_date: ISO date string (optional)
 * - end_date: ISO date string (optional)
 * - provider: Provider name filter (optional)
 * - limit: Number of recent queries to return (default: 100)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "overall": {
 *       "totalRequests": 150,
 *       "successfulRequests": 145,
 *       "failedRequests": 5,
 *       "successRate": "96.67",
 *       "totalTokens": 123456,
 *       "totalCost": "1.2345",
 *       "avgResponseTime": 850,
 *       "avgFaqItems": "3.2"
 *     },
 *     "byProvider": [...],
 *     "recent": [...],
 *     "daily": [...]
 *   }
 * }
 */
router.get('/llm-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      start_date: startDate,
      end_date: endDate,
      provider,
      limit = 100
    } = req.query;

    const stats = analyticsService.getLLMStats({
      startDate,
      endDate,
      provider,
      limit: parseInt(limit, 10)
    });

    sendSuccess(res, stats, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/provider-comparison
 *
 * Compare performance across LLM providers (last 30 days)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": [
 *     {
 *       "provider": "gemini",
 *       "totalRequests": 100,
 *       "successRate": "98.00",
 *       "totalTokens": 50000,
 *       "totalCost": "0.1250",
 *       "avgResponseTime": 450,
 *       "costPerRequest": "0.001250"
 *     }
 *   ]
 * }
 */
router.get('/provider-comparison', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const comparison = analyticsService.getProviderComparison();

    sendSuccess(res, comparison, 200, {
      timestamp: new Date().toISOString(),
      period: 'Last 30 days'
    });
  } catch (error) {
    next(error);
  }
});


/**
 * GET /api/v1/analytics/faq-insights
 *
 * Returns aggregated FAQ insights for the SKIDIY platform.
 * Data is generated by the analytics worker and stored as JSON.
 */
router.get('/faq-insights', requireApiKey(), async (req, res, next) => {
  try {
    const summaryPath =
      process.env.FAQ_INSIGHTS_PATH ||
      path.join(__dirname, '../../../data/analytics_summary.json');

    let payloadRaw;
    try {
      payloadRaw = await fs.readFile(summaryPath, 'utf-8');
    } catch (readError) {
      throw new AppError(
        'FAQ_INSIGHTS_NOT_READY',
        'FAQ insights summary file is not available. Ensure analytics worker has generated the file.',
        503,
        { summaryPath }
      );
    }

    let payload;
    try {
      payload = JSON.parse(payloadRaw);
    } catch (parseError) {
      throw new AppError(
        'FAQ_INSIGHTS_INVALID',
        'FAQ insights summary file contains invalid JSON.',
        500,
        { summaryPath }
      );
    }

    if (!payload || typeof payload !== 'object') {
      throw new AppError(
        'FAQ_INSIGHTS_INVALID',
        'FAQ insights payload is missing or malformed.',
        500,
        { summaryPath }
      );
    }

    const {
      topViewedResorts = [],
      topInteractedFaqs = [],
      generated_at: generatedAt = null
    } = payload;

    sendSuccess(
      res,
      {
        topViewedResorts,
        topInteractedFaqs,
        generated_at: generatedAt
      },
      200,
      {
        timestamp: new Date().toISOString(),
        source: 'analytics-summary'
      }
    );
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/popular-queries
 *
 * Get most popular queries (last 7 days)
 *
 * Query params:
 * - limit: Number of queries to return (default: 10)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": [
 *     {
 *       "query_text": "小朋友幾歲可以學滑雪",
 *       "count": 15,
 *       "avg_tokens": 850,
 *       "avg_response_time": 650
 *     }
 *   ]
 * }
 */
router.get('/popular-queries', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { limit = 10 } = req.query;

    const queries = analyticsService.getPopularQueries(parseInt(limit, 10));

    sendSuccess(res, queries, 200, {
      timestamp: new Date().toISOString(),
      period: 'Last 7 days'
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/cost-report
 *
 * Get detailed cost breakdown by provider and model
 *
 * Query params:
 * - start_date: ISO date string (optional)
 * - end_date: ISO date string (optional)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "totalCost": "2.5678",
 *     "byProvider": {
 *       "gemini": {
 *         "cost": "0.1250",
 *         "requests": 100,
 *         "avgCostPerRequest": "0.001250"
 *       },
 *       "claude": {...}
 *     },
 *     "projectedMonthlyCost": "75.00"
 *   }
 * }
 */
router.get('/cost-report', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      start_date: startDate,
      end_date: endDate
    } = req.query;

    // Get stats for cost calculation
    const stats = analyticsService.getLLMStats({ startDate, endDate });

    // Calculate cost breakdown
    const byProvider = {};
    for (const provider of stats.byProvider) {
      byProvider[provider.provider] = {
        cost: (provider.cost || 0).toFixed(4),
        requests: provider.requests,
        avgCostPerRequest: provider.requests > 0
          ? ((provider.cost || 0) / provider.requests).toFixed(6)
          : '0.000000'
      };
    }

    // Project monthly cost (assuming current rate)
    const daysOfData = stats.daily.length || 1;
    const avgDailyCost = parseFloat(stats.overall.totalCost) / daysOfData;
    const projectedMonthlyCost = (avgDailyCost * 30).toFixed(2);

    const costReport = {
      totalCost: stats.overall.totalCost,
      byProvider,
      projectedMonthlyCost,
      dataPoints: {
        startDate: startDate || stats.daily[stats.daily.length - 1]?.date,
        endDate: endDate || stats.daily[0]?.date,
        totalDays: daysOfData
      }
    };

    sendSuccess(res, costReport, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/export
 *
 * Export analytics data as CSV
 *
 * Query params:
 * - type: Export type (llm_usage | provider_stats)
 * - start_date: ISO date string (optional)
 * - end_date: ISO date string (optional)
 *
 * Response: CSV file download
 */
router.get('/export', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      type = 'llm_usage',
      start_date: startDate,
      end_date: endDate
    } = req.query;

    // Get data
    const stats = analyticsService.getLLMStats({ startDate, endDate, limit: 10000 });

    let csv = '';
    let filename = '';

    if (type === 'llm_usage') {
      // Generate CSV for LLM usage
      csv = 'Timestamp,Query,Provider,Model,Tokens,Cost,Response Time,Success\n';
      for (const row of stats.recent) {
        csv += `"${row.timestamp}","${row.query_text.replace(/"/g, '""')}",${row.provider},${row.model},${row.total_tokens},${row.cost_usd || 0},${row.response_time_ms},${row.success}\n`;
      }
      filename = `llm-usage-${new Date().toISOString().split('T')[0]}.csv`;
    } else if (type === 'provider_stats') {
      // Generate CSV for provider comparison
      csv = 'Provider,Requests,Success Rate,Total Tokens,Total Cost,Avg Response Time,Cost Per Request\n';
      const comparison = analyticsService.getProviderComparison();
      for (const row of comparison) {
        csv += `${row.provider},${row.totalRequests},${row.successRate}%,${row.totalTokens},${row.totalCost},${row.avgResponseTime}ms,${row.costPerRequest}\n`;
      }
      filename = `provider-stats-${new Date().toISOString().split('T')[0]}.csv`;
    }

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(csv);
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/alerts/check
 *
 * Check all alert conditions and return triggered alerts
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "alerts": [
 *       {
 *         "type": "DAILY_COST_EXCEEDED",
 *         "severity": "warning",
 *         "message": "每日成本已達 $12.50（限額：$10.00）",
 *         "data": {...},
 *         "timestamp": "2025-10-13T..."
 *       }
 *     ],
 *     "status": {...}
 *   }
 * }
 */
router.get('/alerts/check', async (req, res, next) => {
  try {
    if (!alertService) {
      throw new AppError('SERVICE_UNAVAILABLE', '警報服務尚未初始化', 503);
    }

    const alerts = await alertService.checkAlerts();
    const status = alertService.getAlertStatus();

    sendSuccess(res, {
      alerts,
      status
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/alerts/status
 *
 * Get current alert configuration and status
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "enabled": true,
 *     "config": {...},
 *     "lastAlerts": {...}
 *   }
 * }
 */
router.get('/alerts/status', async (req, res, next) => {
  try {
    if (!alertService) {
      throw new AppError('SERVICE_UNAVAILABLE', '警報服務尚未初始化', 503);
    }

    const status = alertService.getAlertStatus();

    sendSuccess(res, status, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * PUT /api/v1/analytics/alerts/config
 *
 * Update alert configuration
 *
 * Request body:
 * {
 *   "dailyCostLimit": 15.0,
 *   "monthlyCostLimit": 400.0,
 *   "hourlyRequestLimit": 150,
 *   "errorRateThreshold": 15,
 *   "alertCooldown": 30,
 *   "enabled": true
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "config": {...}
 *   }
 * }
 */
router.put('/alerts/config', async (req, res, next) => {
  try {
    if (!alertService) {
      throw new AppError('SERVICE_UNAVAILABLE', '警報服務尚未初始化', 503);
    }

    const {
      dailyCostLimit,
      monthlyCostLimit,
      hourlyRequestLimit,
      errorRateThreshold,
      alertCooldown,
      enabled
    } = req.body;

    const newConfig = {};

    if (dailyCostLimit !== undefined) newConfig.dailyCostLimit = parseFloat(dailyCostLimit);
    if (monthlyCostLimit !== undefined) newConfig.monthlyCostLimit = parseFloat(monthlyCostLimit);
    if (hourlyRequestLimit !== undefined) newConfig.hourlyRequestLimit = parseInt(hourlyRequestLimit);
    if (errorRateThreshold !== undefined) newConfig.errorRateThreshold = parseFloat(errorRateThreshold);
    if (alertCooldown !== undefined) newConfig.alertCooldown = parseInt(alertCooldown);
    if (enabled !== undefined) newConfig.enabled = Boolean(enabled);

    alertService.updateConfig(newConfig);

    sendSuccess(res, {
      config: alertService.config
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/hot-faqs
 *
 * Get most clicked/viewed FAQs (hot/trending FAQs)
 *
 * Query params:
 * - limit: Number of FAQs to return (default: 5)
 * - days: Number of days to look back (default: 7)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "hot_faqs": [
 *       {
 *         "faq_id": "faq.booking.001",
 *         "views": 150,
 *         "clicks": 120,
 *         "click_rate": 0.8
 *       }
 *     ]
 *   }
 * }
 */
router.get('/hot-faqs', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const limit = parseInt(req.query.limit) || 5;
    const days = parseInt(req.query.days) || 7;
    const languageFilter = req.query.language || null;

    const db = analyticsService.db;
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - days);

    // Get FAQs with most clicks in the last N days
    let hotQuery = `
      SELECT
        faq_id,
        COUNT(*) as views,
        SUM(CASE WHEN clicked = 1 THEN 1 ELSE 0 END) as clicks,
        ROUND(CAST(SUM(CASE WHEN clicked = 1 THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*), 2) as click_rate
      FROM faq_views
      WHERE timestamp >= ?
    `;

    const params = [cutoffDate.toISOString()];
    if (languageFilter) {
      hotQuery += ` AND language = ?`;
      params.push(languageFilter);
    }

    hotQuery += `
      GROUP BY faq_id
      ORDER BY clicks DESC, views DESC
      LIMIT ?
    `;
    params.push(limit);

    const hotFAQs = db.prepare(hotQuery).all(...params);

    const byLanguage = db.prepare(`
      SELECT
        language,
        COUNT(*) as views,
        SUM(CASE WHEN clicked = 1 THEN 1 ELSE 0 END) as clicks
      FROM faq_views
      WHERE timestamp >= ?
      ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY language
      ORDER BY clicks DESC
    `).all(languageFilter ? [cutoffDate.toISOString(), languageFilter] : [cutoffDate.toISOString()]);

    sendSuccess(res, {
      hot_faqs: hotFAQs,
      period_days: days,
      total_faqs: hotFAQs.length,
      language: languageFilter || 'all',
      by_language: byLanguage
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/track-faq-view
 *
 * Track FAQ view/click event
 *
 * Body:
 * {
 *   "faq_id": "faq.booking.001",
 *   "clicked": true,
 *   "query_id": 123,
 *   "position": 1,
 *   "time_to_click_ms": 1500
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": { "tracked": true }
 * }
 */
router.post('/track-faq-view', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { faq_id, clicked, query_id, position, time_to_click_ms, language = 'zh' } = req.body;

    if (!faq_id) {
      throw new AppError('VALIDATION_ERROR', 'faq_id 為必填欄位', 400);
    }

    const db = analyticsService.db;

    // Insert view record
    const stmt = db.prepare(`
      INSERT INTO faq_views (faq_id, query_id, position, clicked, time_to_click_ms, language)
      VALUES (?, ?, ?, ?, ?, ?)
    `);

    stmt.run(
      faq_id,
      query_id || null,
      position || 0,
      clicked ? 1 : 0,
      time_to_click_ms || null,
      language || 'zh'
    );

    sendSuccess(res, {
      tracked: true,
      faq_id
    }, 201, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/track-section-view
 *
 * Track section click event
 *
 * Body:
 * {
 *   "section": "booking",
 *   "language": "zh"
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": { "tracked": true }
 * }
 */
router.post('/track-section-view', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { section, language = 'zh' } = req.body;

    if (!section) {
      throw new AppError('VALIDATION_ERROR', 'section 為必填欄位', 400);
    }

    const db = analyticsService.db;

    // Insert section view record
    const stmt = db.prepare(`
      INSERT INTO section_views (section, language)
      VALUES (?, ?)
    `);

    stmt.run(section, language);

    sendSuccess(res, {
      tracked: true,
      section
    }, 201, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/section-stats
 *
 * Get section click statistics
 *
 * Query params:
 * - days: Number of days to look back (default: 30)
 * - language: Filter by language (optional)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "total": 150,
 *     "by_section": [
 *       {"section": "booking", "clicks": 50, "percentage": "33.33"},
 *       {"section": "gear", "clicks": 30, "percentage": "20.00"}
 *     ],
 *     "by_language": [...],
 *     "daily": [...]
 *   }
 * }
 */
router.get('/section-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { days = 30, language } = req.query;
    const db = analyticsService.db;

    const daysAgo = new Date();
    daysAgo.setDate(daysAgo.getDate() - parseInt(days, 10));
    const dateFilter = daysAgo.toISOString();

    // Total clicks
    let totalQuery = `SELECT COUNT(*) as total FROM section_views WHERE timestamp >= ?`;
    const params = [dateFilter];

    if (language) {
      totalQuery += ` AND language = ?`;
      params.push(language);
    }

    const totalResult = db.prepare(totalQuery).get(...params);
    const total = totalResult.total;

    // By section
    let bySectionQuery = `
      SELECT
        section,
        COUNT(*) as clicks,
        ROUND(COUNT(*) * 100.0 / ?, 2) as percentage
      FROM section_views
      WHERE timestamp >= ?
    `;
    const bySectionParams = [total, dateFilter];

    if (language) {
      bySectionQuery += ` AND language = ?`;
      bySectionParams.push(language);
    }

    bySectionQuery += ` GROUP BY section ORDER BY clicks DESC`;

    const bySection = db.prepare(bySectionQuery).all(...bySectionParams);

    // By language
    const byLanguageQuery = `
      SELECT
        language,
        COUNT(*) as clicks
      FROM section_views
      WHERE timestamp >= ?
      ${language ? 'AND language = ?' : ''}
      GROUP BY language
      ORDER BY clicks DESC
    `;
    const byLanguage = db.prepare(byLanguageQuery).all(language ? [dateFilter, language] : [dateFilter]);

    // Daily stats
    const dailyQuery = `
      SELECT
        DATE(timestamp) as date,
        section,
        COUNT(*) as clicks
      FROM section_views
      WHERE timestamp >= ?
      ${language ? 'AND language = ?' : ''}
      GROUP BY DATE(timestamp), section
      ORDER BY date DESC, clicks DESC
      LIMIT 100
    `;
    const daily = db.prepare(dailyQuery).all(language ? [dateFilter, language] : [dateFilter]);

    sendSuccess(res, {
      total,
      by_section: bySection,
      by_language: byLanguage,
      daily,
      period_days: parseInt(days, 10),
      language: language || 'all'
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/faq-stats
 *
 * Get detailed FAQ click statistics
 *
 * Query params:
 * - days: Number of days to look back (default: 30)
 * - clicked_only: Only include clicked FAQs (default: true)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "total_views": 500,
 *     "total_clicks": 300,
 *     "click_through_rate": "60.00",
 *     "by_faq": [...],
 *     "daily": [...]
 *   }
 * }
 */
router.get('/faq-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { days = 30, clicked_only = 'true', language } = req.query;
    const db = analyticsService.db;

    const daysAgo = new Date();
    daysAgo.setDate(daysAgo.getDate() - parseInt(days, 10));
    const dateFilter = daysAgo.toISOString();

    // Total views and clicks
    let totalsQuery = `
      SELECT
        COUNT(*) as total_views,
        SUM(clicked) as total_clicks
      FROM faq_views
      WHERE timestamp >= ?
    `;
    const totalsParams = [dateFilter];
    if (language) {
      totalsQuery += ` AND language = ?`;
      totalsParams.push(language);
    }
    const totals = db.prepare(totalsQuery).get(...totalsParams);
    const clickThroughRate = totals.total_views > 0
      ? ((totals.total_clicks / totals.total_views) * 100).toFixed(2)
      : '0.00';

    // By FAQ
    let byFaqQuery = `
      SELECT
        faq_id,
        COUNT(*) as views,
        SUM(clicked) as clicks,
        ROUND(SUM(clicked) * 100.0 / COUNT(*), 2) as ctr
      FROM faq_views
      WHERE timestamp >= ?
    `;
    const byFaqParams = [dateFilter];
    if (language) {
      byFaqQuery += ` AND language = ?`;
      byFaqParams.push(language);
    }
    if (clicked_only === 'true') {
      byFaqQuery += ` AND clicked = 1`;
    }

    byFaqQuery += ` GROUP BY faq_id ORDER BY clicks DESC LIMIT 50`;

    const byFaq = db.prepare(byFaqQuery).all(...byFaqParams);

    // Enrich FAQ data with titles from faq_kb.js
    const faqKB = require('../data/faq_kb.js');
    const faqMap = {};
    if (faqKB && faqKB.items) {
      faqKB.items.forEach(item => {
        faqMap[item.id] = {
          title: item.canonical_question || item.id,
          section: item.section || ''
        };
      });
    }

    // Add titles to FAQ stats
    const enrichedByFaq = byFaq.map(faq => ({
      ...faq,
      title: faqMap[faq.faq_id]?.title || faq.faq_id,
      section: faqMap[faq.faq_id]?.section || ''
    }));

    // Daily stats
    let dailyQuery = `
      SELECT
        DATE(timestamp) as date,
        COUNT(*) as views,
        SUM(clicked) as clicks
      FROM faq_views
      WHERE timestamp >= ?
    `;
    const dailyParams = [dateFilter];
    if (language) {
      dailyQuery += ` AND language = ?`;
      dailyParams.push(language);
    }
    if (clicked_only === 'true') {
      dailyQuery += ` AND clicked = 1`;
    }
    dailyQuery += ` GROUP BY DATE(timestamp) ORDER BY date DESC`;
    const daily = db.prepare(dailyQuery).all(...dailyParams);

    const byLanguage = db.prepare(`
      SELECT
        language,
        COUNT(*) as views,
        SUM(clicked) as clicks
      FROM faq_views
      WHERE timestamp >= ?
      ${language ? 'AND language = ?' : ''}
      GROUP BY language
      ORDER BY clicks DESC
    `).all(language ? [dateFilter, language] : [dateFilter]);

    sendSuccess(res, {
      total_views: totals.total_views,
      total_clicks: totals.total_clicks,
      click_through_rate: clickThroughRate,
      by_faq: enrichedByFaq,
      daily,
      by_language: byLanguage,
      period_days: parseInt(days, 10),
      language: language || 'all'
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/track-tag-click
 *
 * Track tag click event (FAQ tags or Resort amenity tags)
 *
 * Body:
 * {
 *   "tag_type": "faq" | "resort",
 *   "tag_name": "#課程預約",
 *   "item_id": "faq.booking.001",
 *   "language": "zh"
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": { "tracked": true }
 * }
 */
router.post('/track-tag-click', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { tag_type, tag_name, item_id, language } = req.body;

    if (!tag_type || !tag_name || !item_id) {
      throw new AppError('VALIDATION_ERROR', 'tag_type, tag_name, item_id 為必填欄位', 400);
    }

    if (!['faq', 'resort'].includes(tag_type)) {
      throw new AppError('VALIDATION_ERROR', 'tag_type 必須為 "faq" 或 "resort"', 400);
    }

    const db = analyticsService.db;

    // Insert tag click record
    const stmt = db.prepare(`
      INSERT INTO tag_clicks (tag_type, tag_name, item_id, language)
      VALUES (?, ?, ?, ?)
    `);

    stmt.run(
      tag_type,
      tag_name,
      item_id,
      language || 'zh'
    );

    sendSuccess(res, {
      tracked: true,
      tag_type,
      tag_name,
      item_id
    }, 201, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/tag-stats
 *
 * Get tag click statistics
 *
 * Query params:
 * - tag_type: Filter by tag type ('faq' or 'resort')
 * - days: Number of days to look back (default: 7)
 * - limit: Number of top tags to return (default: 20)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "by_tag": [
 *       {
 *         "tag_name": "#課程預約",
 *         "tag_type": "faq",
 *         "clicks": 45,
 *         "unique_items": 12
 *       }
 *     ],
 *     "by_type": [
 *       { "tag_type": "faq", "total_clicks": 150 },
 *       { "tag_type": "resort", "total_clicks": 80 }
 *     ],
 *     "daily": [...],
 *     "period_days": 7
 *   }
 * }
 */
router.get('/tag-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const tagType = req.query.tag_type;
    const days = parseInt(req.query.days) || 7;
    const limit = parseInt(req.query.limit) || 20;
    const languageFilter = req.query.language || null;

    const db = analyticsService.db;
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - days);

    // Get tag click statistics
    let byTagQuery = `
      SELECT
        tag_name,
        tag_type,
        COUNT(*) as clicks,
        COUNT(DISTINCT item_id) as unique_items
      FROM tag_clicks
      WHERE timestamp >= ?
    `;

    const params = [cutoffDate.toISOString()];

    if (tagType) {
      byTagQuery += ` AND tag_type = ?`;
      params.push(tagType);
    }

    if (languageFilter) {
      byTagQuery += ` AND language = ?`;
      params.push(languageFilter);
    }

    byTagQuery += `
      GROUP BY tag_name, tag_type
      ORDER BY clicks DESC
      LIMIT ?
    `;
    params.push(limit);

    const byTag = db.prepare(byTagQuery).all(...params);

    // Get statistics by tag type
    const typeQueryParams = [cutoffDate.toISOString()];
    if (tagType) typeQueryParams.push(tagType);
    if (languageFilter) typeQueryParams.push(languageFilter);

    const byType = db.prepare(`
      SELECT
        tag_type,
        COUNT(*) as total_clicks,
        COUNT(DISTINCT tag_name) as unique_tags,
        COUNT(DISTINCT item_id) as unique_items
      FROM tag_clicks
      WHERE timestamp >= ?
      ${tagType ? 'AND tag_type = ?' : ''}
      ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY tag_type
      ORDER BY total_clicks DESC
    `).all(...typeQueryParams);

    // Get daily statistics
    const dailyParams = [cutoffDate.toISOString()];
    if (tagType) dailyParams.push(tagType);
    if (languageFilter) dailyParams.push(languageFilter);

    const daily = db.prepare(`
      SELECT
        DATE(timestamp) as date,
        tag_type,
        COUNT(*) as clicks
      FROM tag_clicks
      WHERE timestamp >= ?
      ${tagType ? 'AND tag_type = ?' : ''}
      ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY DATE(timestamp), tag_type
      ORDER BY date DESC
    `).all(...dailyParams);

    const languageParams = [cutoffDate.toISOString()];
    if (tagType) languageParams.push(tagType);
    if (languageFilter) languageParams.push(languageFilter);

    const byLanguage = db.prepare(`
      SELECT
        language,
        COUNT(*) as clicks,
        COUNT(DISTINCT tag_name) as unique_tags
      FROM tag_clicks
      WHERE timestamp >= ?
      ${tagType ? 'AND tag_type = ?' : ''}
      ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY language
      ORDER BY clicks DESC
    `).all(...languageParams);

    sendSuccess(res, {
      by_tag: byTag,
      by_type: byType,
      daily,
      by_language: byLanguage,
      period_days: days,
      language: languageFilter || 'all'
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/track-resort-click
 *
 * Track resort region or card click event
 *
 * Body:
 * {
 *   "click_type": "region" | "resort_card",
 *   "region": "Hokkaido Prefecture",  // for region clicks
 *   "resort_id": "resort_id",          // for resort_card clicks
 *   "language": "zh"
 * }
 *
 * Response:
 * {
 *   "success": true,
 *   "data": { "tracked": true }
 * }
 */
router.post('/track-resort-click', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { click_type, region, resort_id, language } = req.body;

    if (!click_type) {
      throw new AppError('VALIDATION_ERROR', 'click_type 為必填欄位', 400);
    }

    if (!['region', 'resort_card'].includes(click_type)) {
      throw new AppError('VALIDATION_ERROR', 'click_type 必須為 "region" 或 "resort_card"', 400);
    }

    if (click_type === 'region' && !region) {
      throw new AppError('VALIDATION_ERROR', 'region 為必填欄位 (當 click_type 為 region 時)', 400);
    }

    if (click_type === 'resort_card' && !resort_id) {
      throw new AppError('VALIDATION_ERROR', 'resort_id 為必填欄位 (當 click_type 為 resort_card 時)', 400);
    }

    const db = analyticsService.db;

    // Insert resort click record
    const stmt = db.prepare(`
      INSERT INTO resort_clicks (click_type, region, resort_id, language)
      VALUES (?, ?, ?, ?)
    `);

    stmt.run(
      click_type,
      region || null,
      resort_id || null,
      language || 'zh'
    );

    sendSuccess(res, {
      tracked: true,
      click_type,
      region: region || null,
      resort_id: resort_id || null
    }, 201, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/resort-stats
 *
 * Get resort click statistics
 *
 * Query params:
 * - click_type: Filter by click type ('region' or 'resort_card')
 * - days: Number of days to look back (default: 7)
 * - limit: Number of top items to return (default: 20)
 *
 * Response:
 * {
 *   "success": true,
 *   "data": {
 *     "by_type": [
 *       { "click_type": "region", "total_clicks": 145 },
 *       { "click_type": "resort_card", "total_clicks": 98 }
 *     ],
 *     "top_regions": [
 *       { "region": "Hokkaido Prefecture", "clicks": 45 }
 *     ],
 *     "top_resorts": [
 *       { "resort_id": "niseko_grand_hirafu", "clicks": 28 }
 *     ],
 *     "daily": [...],
 *     "period_days": 7
 *   }
 * }
 */
router.get('/resort-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const clickType = req.query.click_type;
    const days = parseInt(req.query.days) || 7;
    const limit = parseInt(req.query.limit) || 20;
    const languageFilter = req.query.language || null;

    const db = analyticsService.db;
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - days);

    // Statistics by type
    const byTypeParams = [cutoffDate.toISOString()];
    if (clickType) byTypeParams.push(clickType);
    if (languageFilter) byTypeParams.push(languageFilter);

    const byType = db.prepare(`
      SELECT
        click_type,
        COUNT(*) as total_clicks
      FROM resort_clicks
      WHERE timestamp >= ?
      ${clickType ? 'AND click_type = ?' : ''}
      ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY click_type
      ORDER BY total_clicks DESC
    `).all(...byTypeParams);

    // Top regions
    const topRegionParams = [cutoffDate.toISOString()];
    if (languageFilter) topRegionParams.push(languageFilter);

    const topRegions = db.prepare(`
      SELECT
        region,
        COUNT(*) as clicks
      FROM resort_clicks
      WHERE timestamp >= ?
        AND click_type = 'region'
        AND region IS NOT NULL
        ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY region
      ORDER BY clicks DESC
      LIMIT ?
    `).all(...topRegionParams, limit);

    // Top resorts
    const topResortParams = [cutoffDate.toISOString()];
    if (languageFilter) topResortParams.push(languageFilter);

    const topResorts = db.prepare(`
      SELECT
        resort_id,
        COUNT(*) as clicks
      FROM resort_clicks
      WHERE timestamp >= ?
        AND click_type = 'resort_card'
        AND resort_id IS NOT NULL
        ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY resort_id
      ORDER BY clicks DESC
      LIMIT ?
    `).all(...topResortParams, limit);

    // Daily statistics
    const dailyParams = [cutoffDate.toISOString()];
    if (clickType) dailyParams.push(clickType);
    if (languageFilter) dailyParams.push(languageFilter);

    const daily = db.prepare(`
      SELECT
        DATE(timestamp) as date,
        click_type,
        COUNT(*) as clicks
      FROM resort_clicks
      WHERE timestamp >= ?
      ${clickType ? 'AND click_type = ?' : ''}
      ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY DATE(timestamp), click_type
      ORDER BY date DESC
    `).all(...dailyParams);

    const byLanguageParams = [cutoffDate.toISOString()];
    if (clickType) byLanguageParams.push(clickType);
    if (languageFilter) byLanguageParams.push(languageFilter);

    const byLanguage = db.prepare(`
      SELECT
        language,
        COUNT(*) as clicks
      FROM resort_clicks
      WHERE timestamp >= ?
      ${clickType ? 'AND click_type = ?' : ''}
      ${languageFilter ? 'AND language = ?' : ''}
      GROUP BY language
      ORDER BY clicks DESC
    `).all(...byLanguageParams);

    sendSuccess(res, {
      by_type: byType,
      top_regions: topRegions,
      top_resorts: topResorts,
      daily,
      by_language: byLanguage,
      period_days: days,
      language: languageFilter || 'all'
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/track-section-click
 * Track FAQ section/category click
 */
router.post('/track-section-click', async (req, res, next) => {
  try {
    const { section, language } = req.body;

    if (!section) {
      throw new AppError('VALIDATION_ERROR', 'section 為必填欄位', 400);
    }

    const db = analyticsService.db;
    const stmt = db.prepare(`
      INSERT INTO section_views (section, language)
      VALUES (?, ?)
    `);

    stmt.run(section, language || 'zh');

    sendSuccess(res, {
      tracked: true,
      section,
      language: language || 'zh'
    }, 201);
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/section-stats
 * Get section/category click statistics
 */
router.get('/section-stats', async (req, res, next) => {
  try {
    const days = parseInt(req.query.days) || 7;
    const limit = parseInt(req.query.limit) || 20;
    const languageFilter = req.query.language;

    const db = analyticsService.db;
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - days);
    const cutoffISO = cutoffDate.toISOString();

    // Build WHERE clause for language filtering
    const whereClause = languageFilter && languageFilter !== 'all'
      ? 'WHERE timestamp >= ? AND language = ?'
      : 'WHERE timestamp >= ?';
    const params = languageFilter && languageFilter !== 'all'
      ? [cutoffISO, languageFilter]
      : [cutoffISO];

    // Top sections by clicks
    const topSections = db.prepare(`
      SELECT section, COUNT(*) as clicks, language
      FROM section_views
      ${whereClause}
      GROUP BY section, language
      ORDER BY clicks DESC
      LIMIT ?
    `).all(...params, limit);

    // Total clicks per section (all languages)
    const bySection = db.prepare(`
      SELECT section, COUNT(*) as total_clicks,
             COUNT(DISTINCT language) as languages_used
      FROM section_views
      ${whereClause}
      GROUP BY section
      ORDER BY total_clicks DESC
      LIMIT ?
    `).all(...params, limit);

    // Daily trend
    const daily = db.prepare(`
      SELECT DATE(timestamp) as date,
             COUNT(*) as clicks,
             COUNT(DISTINCT section) as unique_sections
      FROM section_views
      ${whereClause}
      GROUP BY DATE(timestamp)
      ORDER BY date DESC
      LIMIT 30
    `).all(...params);

    // By language
    const byLanguageParams = languageFilter && languageFilter !== 'all'
      ? [cutoffISO, languageFilter]
      : [cutoffISO];

    const byLanguage = db.prepare(`
      SELECT language, COUNT(*) as clicks,
             COUNT(DISTINCT section) as unique_sections
      FROM section_views
      WHERE timestamp >= ?
      ${languageFilter && languageFilter !== 'all' ? 'AND language = ?' : ''}
      GROUP BY language
      ORDER BY clicks DESC
    `).all(...byLanguageParams);

    sendSuccess(res, {
      top_sections: topSections,
      by_section: bySection,
      daily,
      by_language: byLanguage,
      period_days: days,
      language: languageFilter || 'all'
    }, 200, {
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    next(error);
  }
});

/**
 * POST /api/v1/analytics/feedback
 * Log user feedback on FAQ or resort
 *
 * Request body:
 * {
 *   "feedback_type": "faq" | "resort",
 *   "item_id": "faq.booking.001",
 *   "helpful": true | false,
 *   "reason": "訊息不完整",  // optional
 *   "comment": "需要更多細節",  // optional
 *   "language": "zh"  // optional, defaults to 'zh'
 * }
 */
router.post('/feedback', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      feedback_type,
      item_id,
      helpful,
      reason,
      comment,
      language
    } = req.body;

    // Validation
    if (!feedback_type || !['faq', 'resort'].includes(feedback_type)) {
      throw new AppError('INVALID_INPUT', 'feedback_type 必須為 "faq" 或 "resort"', 400);
    }

    if (!item_id) {
      throw new AppError('INVALID_INPUT', 'item_id 為必填欄位', 400);
    }

    if (helpful === undefined || helpful === null || typeof helpful !== 'boolean') {
      throw new AppError('INVALID_INPUT', 'helpful 必須為 true 或 false', 400);
    }

    // Log feedback
    const feedbackId = analyticsService.logFeedback({
      feedback_type,
      item_id,
      helpful,
      reason: reason || null,
      comment: comment || null,
      language: language || 'zh',
      user_session_id: req.sessionID || null
    });

    sendSuccess(res, {
      tracked: true,
      feedback_id: feedbackId,
      feedback_type,
      item_id,
      helpful
    }, 201);

  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/feedback-stats
 * Get feedback statistics
 *
 * Query params:
 * - feedback_type: 'faq' | 'resort' (optional)
 * - item_id: specific item ID (optional)
 * - days: number of days to look back (optional, default: all)
 */
router.get('/feedback-stats', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const {
      feedback_type,
      item_id,
      language,
      days
    } = req.query;

    // Get overall stats
    const stats = analyticsService.getFeedbackStats({
      feedback_type,
      item_id,
      language,
      days: days ? parseInt(days, 10) : undefined
    });

    // Get lowest rated items (items with lowest helpful rate)
    const lowestRated = analyticsService.getLowestRatedItems({
      feedback_type,
      language,
      days: days ? parseInt(days, 10) : undefined,
      limit: 10
    });

    // Get feedback reasons distribution
    const reasons = analyticsService.getFeedbackReasons({
      feedback_type,
      language,
      days: days ? parseInt(days, 10) : undefined
    });

    // Get daily trend
    const trend = analyticsService.getFeedbackTrend({
      feedback_type,
      language,
      days: days ? parseInt(days, 10) : undefined
    });

    sendSuccess(res, {
      summary: stats,
      lowest_rated: lowestRated,
      reasons,
      daily_trend: trend,
      filter: {
        feedback_type: feedback_type || 'all',
        item_id: item_id || 'all',
        language: language || 'all',
        days: days || 'all'
      }
    }, 200, {
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/feedback-item/:itemId
 * Get detailed feedback for a specific item
 */
router.get('/feedback-item/:itemId', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { itemId } = req.params;
    const { days, limit = 20 } = req.query;

    // Get stats for this item
    const stats = analyticsService.getFeedbackStats({
      item_id: itemId,
      days: days ? parseInt(days, 10) : undefined
    });

    // Get comments/feedback details
    const comments = analyticsService.getFeedbackComments({
      item_id: itemId,
      limit: parseInt(limit, 10)
    });

    sendSuccess(res, {
      item_id: itemId,
      stats,
      comments,
      comment_count: comments.length
    }, 200);

  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/feedback-reasons
 * Get feedback reasons distribution (negative feedback only)
 *
 * Query params:
 * - feedback_type: 'faq' | 'resort' (optional)
 * - days: number of days to look back (optional)
 */
router.get('/feedback-reasons', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { feedback_type, language, days } = req.query;

    const reasons = analyticsService.getFeedbackReasons({
      feedback_type,
      language,
      days: days ? parseInt(days, 10) : undefined
    });

    sendSuccess(res, reasons, 200);

  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/feedback-top-items
 * Get top rated items (highest helpful rate)
 *
 * Query params:
 * - feedback_type: 'faq' | 'resort' (optional)
 * - language: 'zh' | 'en' | 'th' | 'all' (optional)
 * - days: number of days to look back (optional)
 * - limit: number of items to return (default: 10)
 */
router.get('/feedback-top-items', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { feedback_type, language, days, limit = 10 } = req.query;

    const items = analyticsService.getTopRatedItems({
      feedback_type,
      language,
      days: days ? parseInt(days, 10) : undefined,
      limit: parseInt(limit, 10)
    });

    sendSuccess(res, items, 200);

  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/feedback-bottom-items
 * Get bottom rated items (lowest helpful rate)
 *
 * Query params:
 * - feedback_type: 'faq' | 'resort' (optional)
 * - language: 'zh' | 'en' | 'th' | 'all' (optional)
 * - days: number of days to look back (optional)
 * - limit: number of items to return (default: 10)
 */
router.get('/feedback-bottom-items', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { feedback_type, language, days, limit = 10 } = req.query;

    const items = analyticsService.getLowestRatedItems({
      feedback_type,
      language,
      days: days ? parseInt(days, 10) : undefined,
      limit: parseInt(limit, 10)
    });

    sendSuccess(res, items, 200);

  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/analytics/feedback-recent
 * Get recent feedback records
 *
 * Query params:
 * - feedback_type: 'faq' | 'resort' (optional)
 * - helpful: true | false (optional)
 * - language: 'zh' | 'en' | 'th' | 'all' (optional)
 * - limit: number of records to return (default: 50)
 */
router.get('/feedback-recent', async (req, res, next) => {
  try {
    if (!analyticsService) {
      throw new AppError('SERVICE_UNAVAILABLE', 'Analytics 服務尚未初始化', 503);
    }

    const { feedback_type, helpful, language, limit = 50 } = req.query;

    const feedbacks = analyticsService.getRecentFeedback({
      feedback_type,
      helpful: helpful !== undefined ? helpful === 'true' : undefined,
      language,
      limit: parseInt(limit, 10)
    });

    sendSuccess(res, feedbacks, 200);

  } catch (error) {
    next(error);
  }
});

module.exports = router;
